version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    container_name: keycloak
    command: start-dev --import-realm --metrics-enabled=true
    ports:
      - "9091:9091"
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=POSTGRES
#      - DB_ADDR=host.docker.internal
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - ${GLOBAL_NETWORK:-keycloak}
    depends_on:
      - postgres