server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:localkeystore/edge.p12
    key-store-password: password
    key-alias: localhost

spring:
  flyway:
    enabled: true
  application:
    name: edge-service

  cloud:
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
      routes:
        - id: test
          uri:
            http://locahhost:8443
          predicates:
            - Path="/tenant

        - id: server-route
          uri: http://localhost:8181
          predicates:
            - Host={tenant}.saastemplate
            - Path=/intro/**
          filters:
            - AddRequestHeader=X-TenantId,{tenant}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/root?currentSchema=tenant
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create

logging:
  pattern:
    correlation: '[%X{traceId:-}-%X{spanId:-}] [%X{tenantId:-}] '

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
      "service,name": ${spring.application.name}
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 5s
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always