version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: docman
      POSTGRES_PASSWORD: docman
      POSTGRES_DB: doc-ctrl
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - postgres

  minio:
    image: minio/minio
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: