CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE tenant_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identifier VARCHAR(30) NOT NULL,
    client_id VARCHAR(50) NOT NULL,
    client_secret VARCHAR(150) NOT NULL,
    issuer VARCHAR(150) NOT NULL ,
    CONSTRAINT pk_tenant_config PRIMARY KEY (id)
);

ALTER TABLE tenant_config ADD CONSTRAINT uc_identifier UNIQUE (identifier);

