server:
  port: 8181

spring:
  application:
    name: subscriber-service
  flyway:
    locations: classpath:db/migration/default
    schemas: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
      "service.name": ${spring.application.name}
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 5s
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always

---

spring:
  profiles:

    active: prod
  config:
    import: